[package]
name = "wasm_module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.140"
serde-wasm-bindgen = "0.4"
